export const DND_CLASSES = [
    {
        id: 'barbarian',
        name: 'Barbarian',
        hitDie: 12,
        primaryAbility: ['Strength'],
        saves: ['Strength', 'Constitution'],
    },
    {
        id: 'bard',
        name: 'Bard',
        hitDie: 8,
        primaryAbility: ['Charisma'],
        saves: ['Dexterity', 'Charisma'],
    },
    {
        id: 'cleric',
        name: 'Cleric',
        hitDie: 8,
        primaryAbility: ['Wisdom'],
        saves: ['Wisdom', 'Charisma'],
    },
    {
        id: 'druid',
        name: 'Druid',
        hitDie: 8,
        primaryAbility: ['Wisdom'],
        saves: ['Intelligence', 'Wisdom'],
    },
    {
        id: 'fighter',
        name: 'Fighter',
        hitDie: 10,
        primaryAbility: ['Strength', 'Dexterity'],
        saves: ['Strength', 'Constitution'],
    },
    {
        id: 'monk',
        name: 'Monk',
        hitDie: 8,
        primaryAbility: ['Dexterity', 'Wisdom'],
        saves: ['Strength', 'Dexterity'],
    },
    {
        id: 'paladin',
        name: 'Paladin',
        hitDie: 10,
        primaryAbility: ['Strength', 'Charisma'],
        saves: ['Wisdom', 'Charisma'],
    },
    {
        id: 'ranger',
        name: 'Ranger',
        hitDie: 10,
        primaryAbility: ['Dexterity', 'Wisdom'],
        saves: ['Strength', 'Dexterity'],
    },
    {
        id: 'rogue',
        name: 'Rogue',
        hitDie: 8,
        primaryAbility: ['Dexterity'],
        saves: ['Dexterity', 'Intelligence'],
    },
    {
        id: 'sorcerer',
        name: 'Sorcerer',
        hitDie: 6,
        primaryAbility: ['Charisma'],
        saves: ['Constitution', 'Charisma'],
    },
    {
        id: 'warlock',
        name: 'Warlock',
        hitDie: 8,
        primaryAbility: ['Charisma'],
        saves: ['Wisdom', 'Charisma'],
    },
    {
        id: 'wizard',
        name: 'Wizard',
        hitDie: 6,
        primaryAbility: ['Intelligence'],
        saves: ['Intelligence', 'Wisdom'],
    },
];

export const DND_RACES = [
    { id: 'human', name: 'Human' },
    { id: 'elf', name: 'Elf' },
    { id: 'dwarf', name: 'Dwarf' },
    { id: 'halfling', name: 'Halfling' },
    { id: 'gnome', name: 'Gnome' },
    { id: 'dragonborn', name: 'Dragonborn' },
    { id: 'tiefling', name: 'Tiefling' },
    { id: 'orc', name: 'Orc' },
    { id: 'aasimar', name: 'Aasimar' },
    { id: 'goliath', name: 'Goliath' },
];

export const DND_SKILLS = [
    'Acrobatics',
    'Animal Handling',
    'Arcana',
    'Athletics',
    'Deception',
    'History',
    'Insight',
    'Intimidation',
    'Investigation',
    'Medicine',
    'Nature',
    'Perception',
    'Performance',
    'Persuasion',
    'Religion',
    'Sleight of Hand',
    'Stealth',
    'Survival',
];

export const DND_SUBCLASSES: Record<string, { id: string; name: string }[]> = {
    barbarian: [
        { id: 'berserker', name: 'Path of the Berserker' },
        { id: 'wild_heart', name: 'Path of the Wild Heart' },
        { id: 'world_tree', name: 'Path of the World Tree' },
        { id: 'zealot', name: 'Path of the Zealot' },
    ],
    bard: [
        { id: 'dance', name: 'College of Dance' },
        { id: 'glamour', name: 'College of Glamour' },
        { id: 'lore', name: 'College of Lore' },
        { id: 'valor', name: 'College of Valor' },
    ],
    cleric: [
        { id: 'life', name: 'Life Domain' },
        { id: 'light', name: 'Light Domain' },
        { id: 'trickery', name: 'Trickery Domain' },
        { id: 'war', name: 'War Domain' },
    ],
    druid: [
        { id: 'land', name: 'Circle of the Land' },
        { id: 'moon', name: 'Circle of the Moon' },
        { id: 'sea', name: 'Circle of the Sea' },
        { id: 'stars', name: 'Circle of Stars' },
    ],
    fighter: [
        { id: 'battle_master', name: 'Battle Master' },
        { id: 'champion', name: 'Champion' },
        { id: 'eldritch_knight', name: 'Eldritch Knight' },
        { id: 'psi_warrior', name: 'Psi Warrior' },
    ],
    monk: [
        { id: 'mercy', name: 'Warrior of Mercy' },
        { id: 'shadow', name: 'Warrior of Shadow' },
        { id: 'elements', name: 'Warrior of the Elements' },
        { id: 'open_hand', name: 'Warrior of the Open Hand' },
    ],
    paladin: [
        { id: 'devotion', name: 'Oath of Devotion' },
        { id: 'glory', name: 'Oath of Glory' },
        { id: 'ancients', name: 'Oath of the Ancients' },
        { id: 'vengeance', name: 'Oath of Vengeance' },
    ],
    ranger: [
        { id: 'beast_master', name: 'Beast Master' },
        { id: 'fey_wanderer', name: 'Fey Wanderer' },
        { id: 'gloom_stalker', name: 'Gloom Stalker' },
        { id: 'hunter', name: 'Hunter' },
    ],
    rogue: [
        { id: 'arcane_trickster', name: 'Arcane Trickster' },
        { id: 'assassin', name: 'Assassin' },
        { id: 'soulknife', name: 'Soulknife' },
        { id: 'thief', name: 'Thief' },
    ],
    sorcerer: [
        { id: 'aberrant', name: 'Aberrant Sorcery' },
        { id: 'clockwork', name: 'Clockwork Sorcery' },
        { id: 'draconic', name: 'Draconic Sorcery' },
        { id: 'wild_magic', name: 'Wild Magic Sorcery' },
    ],
    warlock: [
        { id: 'archfey', name: 'Archfey Patron' },
        { id: 'celestial', name: 'Celestial Patron' },
        { id: 'fiend', name: 'Fiend Patron' },
        { id: 'great_old_one', name: 'Great Old One Patron' },
    ],
    wizard: [
        { id: 'abjurer', name: 'Abjurer' },
        { id: 'diviner', name: 'Diviner' },
        { id: 'evoker', name: 'Evoker' },
        { id: 'illusionist', name: 'Illusionist' },
    ],
};
